version: 2.1

orbs:
  docker: circleci/docker@1.2.1
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.0.2

jobs:
  build-and-push:
    executor: docker/docker
    parameters:
      image:
        description: |
          Name of docker image with organization
        type: string
      tag:
        description: |
          Docker image tag
        type: string
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
#      - run: echo 'export VERSION=$(cat VERSION)' >> $BASH_ENV
      - docker/build:
          image: << parameters.image >>
          tag: << parameters.tag >>
      - docker/push:
          image: << parameters.image >>
          tag: << parameters.tag >>

  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    parameters:
      cluster:
        description: |
          Name of gke cluster
        type: string
      container:
        description: |
          Name of docker container with organization
        type: string
      deployment:
        description: |
          Name of k8 deployment
        type: string
      image:
        description: |
          Name of docker image with organization
        type: string
      tag:
        description: |
          Docker image tag
        type: string
    steps:
#      - run: echo 'export VERSION=$(cat VERSION)' >> $BASH_ENV
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: << parameters.cluster >>
          perform-login: true
      - gcp-gke/rollout-image:
          cluster: << parameters.cluster >>
          container: << parameters.container >>
          deployment: << parameters.deployment >>
          image: << parameters.image >>
          tag: << parameters.tag >>
  # test:
  #   description: Run integration tests after deployment is finished
  #   docker:
  #     - image: circleci/golang:latest
  #   parameters:
  #     environment:
  #       description: |
  #         The environment to test
  #       type: string
  #   steps:
  #     - checkout
  #     - run: make test-<< parameters.environment >>

workflows:
  docker-build-push-deploy-dev:
    jobs:
      - build-and-push:
          image: {{<docker_registry>}}/{{<service_name>}}
          # todo: this is a hack since circleCI does not pass env vars into workflows nor orbs
          # todo: the issue here is say this version is the same as the orbs, the orb version
          # todo: will bump too
          # todo: WHAT THE FLYING FUCK.
          tag: 0.0.0
#          tag: $(CIRCLE_SHA1)
#          tag: $(CIRCLE_TAG)
          filters:
             branches:
               only:
                 - dev
#            branches:
#              ignore: /.*/
#            tags:
#              only: /^v.*/
      - deploy:
          cluster: {{<cluster_name>}}-dev
          container: {{<service_name>}}
          deployment: {{<service_name>}}
          image: {{<docker_registry>}}/{{<service_name>}}
          # todo: this is a hack since circleCI does not pass env vars into workflows nor orbs
          # todo: the issue here is say this version is the same as the orbs, the orb version
          # todo: will bump too
          # todo: WHAT THE FLYING FUCK.
          tag: 0.0.0
#          tag: $(CIRCLE_SHA1)
          # tag: $(CIRCLE_TAG)
          filters:
             branches:
               only:
                 - dev
#            branches:
#              ignore: /.*/
#            tags:
#              only: /^v.*/
          requires:
            - build-and-push
      # - test:
      #     environment: dev
      #     filters:
      #       branches:
      #         only:
      #           - dev
      #     requires:
      #       - deploy
  docker-build-push-deploy-prod:
    jobs:
#      - build-and-push:
#          image: {{<docker_registry>}}/{{<service_name>}}
#          tag: 0.0.0
#          filters:
#            branches:
#              only:
#                - prod
      - deploy:
          cluster: {{<cluster_name>}}
          container: {{<service_name>}}
          deployment: {{<service_name>}}
          image: {{<docker_registry>}}/{{<service_name>}}
          tag: 0.0.0
          filters:
            branches:
              only:
                - prod
#          requires:
#            - build-and-push
      # - test:
      #     environment: prod
      #     filters:
      #       branches:
      #         only:
      #           - prod
      #     requires:
      #       - deploy
