apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.service_name}}
  name: {{.service_name}}
spec:
  type: LoadBalancer
  ports:
    - port: {{.port}}
      targetPort: {{.port}}
      protocol: TCP
  selector:
    app: {{.service_name}}
